# SPRING DATA PROPERTIES
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://github.com/KelvinSpatola
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    #url: jdbc:mysql://localhost://3306/rest_with_spring_boot_udemy?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    
# SWAGGER OPEN-API PROPERTIES
springdoc:
  pathsToMatch: 
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true